version: '3'
services:
  se-server:
    build: ./docker/se-server-rcn
    hostname: se-server
    tty: true
    privileged: true
  echo:
    build: ./docker/se-echo-rcn
    hostname: echo
    tty: true
    privileged: true
    links:
      - se-server
  web:
    build: ./docker/se-web-rcn
    hostname: web
    tty: true
    privileged: true
    links:
      - se-server
      - echo
    ports:
      - 8080:8080
